// Generated by Phase 14.6a. Do not hand-edit.
// Six-dot Braille ASCII -> Unicode Braille Patterns.

export const BRAILLE_ASCII_6DOT_DOTS = {
  " ": [],
  "!": [
    2,
    3,
    4,
    6
  ],
  "\"": [
    5
  ],
  "#": [
    3,
    4,
    5,
    6
  ],
  "$": [
    1,
    2,
    4,
    6
  ],
  "%": [
    1,
    4,
    6
  ],
  "&": [
    1,
    2,
    3,
    4,
    6
  ],
  "'": [
    3
  ],
  "(": [
    1,
    2,
    3,
    5,
    6
  ],
  ")": [
    2,
    3,
    4,
    5,
    6
  ],
  "*": [
    1,
    6
  ],
  "+": [
    3,
    4,
    6
  ],
  ",": [
    6
  ],
  "-": [
    3,
    6
  ],
  ".": [
    4,
    6
  ],
  "/": [
    3,
    4
  ],
  "0": [
    3,
    5,
    6
  ],
  "1": [
    2
  ],
  "2": [
    2,
    3
  ],
  "3": [
    2,
    5
  ],
  "4": [
    2,
    5,
    6
  ],
  "5": [
    2,
    6
  ],
  "6": [
    2,
    3,
    5
  ],
  "7": [
    2,
    3,
    5,
    6
  ],
  "8": [
    2,
    3,
    6
  ],
  "9": [
    3,
    5
  ],
  ":": [
    1,
    5,
    6
  ],
  ";": [
    5,
    6
  ],
  "<": [
    1,
    2,
    6
  ],
  "=": [
    1,
    2,
    3,
    4,
    5,
    6
  ],
  ">": [
    3,
    4,
    5
  ],
  "?": [
    1,
    4,
    5,
    6
  ],
  "@": [
    4
  ],
  "A": [
    1
  ],
  "B": [
    1,
    2
  ],
  "C": [
    1,
    4
  ],
  "D": [
    1,
    4,
    5
  ],
  "E": [
    1,
    5
  ],
  "F": [
    1,
    2,
    4
  ],
  "G": [
    1,
    2,
    4,
    5
  ],
  "H": [
    1,
    2,
    5
  ],
  "I": [
    2,
    4
  ],
  "J": [
    2,
    4,
    5
  ],
  "K": [
    1,
    3
  ],
  "L": [
    1,
    2,
    3
  ],
  "M": [
    1,
    3,
    4
  ],
  "N": [
    1,
    3,
    4,
    5
  ],
  "O": [
    1,
    3,
    5
  ],
  "P": [
    1,
    2,
    3,
    4
  ],
  "Q": [
    1,
    2,
    3,
    4,
    5
  ],
  "R": [
    1,
    2,
    3,
    5
  ],
  "S": [
    2,
    3,
    4
  ],
  "T": [
    2,
    3,
    4,
    5
  ],
  "U": [
    1,
    3,
    6
  ],
  "V": [
    1,
    2,
    3,
    6
  ],
  "W": [
    2,
    4,
    5,
    6
  ],
  "X": [
    1,
    3,
    4,
    6
  ],
  "Y": [
    1,
    3,
    4,
    5,
    6
  ],
  "Z": [
    1,
    3,
    5,
    6
  ],
  "[": [
    2,
    4,
    6
  ],
  "\\": [
    1,
    2,
    5,
    6
  ],
  "]": [
    1,
    2,
    4,
    5,
    6
  ],
  "^": [
    4,
    5
  ],
  "_": [
    4,
    5,
    6
  ]
} as const;

export type CanonicalBrailleAsciiChar = keyof typeof BRAILLE_ASCII_6DOT_DOTS;

function fail(message: string): never {
  throw new Error(`MUSIC_BRAILLE_ASCII_ERROR: ${message}`);
}

export function dotsToUnicodeBraille(dots: readonly number[]): string {
  let mask = 0;
  const seen = new Set<number>();
  for (const dot of dots) {
    if (!Number.isInteger(dot) || dot < 1 || dot > 6) {
      fail(`invalid six-dot Braille dot number: ${dot}`);
    }
    if (seen.has(dot)) {
      fail(`duplicate six-dot Braille dot number: ${dot}`);
    }
    seen.add(dot);
    mask |= 1 << (dot - 1);
  }
  return String.fromCodePoint(0x2800 + mask);
}

export function canonicalizeBrailleAsciiChar(char: string): CanonicalBrailleAsciiChar {
  if (char.length !== 1) {
    fail(`expected one character, got length ${char.length}`);
  }

  const code = char.charCodeAt(0);
  let canonical = char;
  if (code >= 97 && code <= 122) {
    canonical = char.toUpperCase();
  }

  if (!Object.prototype.hasOwnProperty.call(BRAILLE_ASCII_6DOT_DOTS, canonical)) {
    fail(`unsupported Braille ASCII character U+${code.toString(16).toUpperCase().padStart(4, "0")}`);
  }

  return canonical as CanonicalBrailleAsciiChar;
}

export function brailleAsciiCharToUnicode(char: string): string {
  const canonical = canonicalizeBrailleAsciiChar(char);
  return dotsToUnicodeBraille(BRAILLE_ASCII_6DOT_DOTS[canonical]);
}

export function brfAsciiToUnicode(input: string): string {
  const normalized = input.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
  let out = "";

  for (const char of normalized) {
    if (char === "\n" || char === "\f") {
      out += char;
      continue;
    }
    out += brailleAsciiCharToUnicode(char);
  }

  return out;
}

export function isUnicodeBraillePattern(char: string): boolean {
  if ([...char].length !== 1) return false;
  const cp = char.codePointAt(0);
  return cp !== undefined && cp >= 0x2800 && cp <= 0x28ff;
}
