// Generated by Phase 14.6b. Do not hand-edit.
// Stateful MIDI-profile Music Braille encoder.
// NotationScore integration remains Phase 14.7.

import { brfAsciiToUnicode } from "./braille-ascii.js";
import {
  encodeAtomicChord,
  encodeAtomicNote,
  encodeAtomicRest,
  fullMeasureInAccordBrf,
  partMeasureInAccordBrf,
  keySignatureBrf,
  simpleMeterBrf,
  transcriberAddedRestPrefixBrf,
  type AtomicChordIntervalInput,
  type BrailleEmission,
  type ExplicitAccidental,
  type MusicNoteName,
  type MusicValue,
} from "./music-braille-atomic-encoder.js";

export const KEY_SIGNATURE_SHARP_ORDER = ["F", "C", "G", "D", "A", "E", "B"] as const;
export const KEY_SIGNATURE_FLAT_ORDER = ["B", "E", "A", "D", "G", "C", "F"] as const;
export const SPELLING_ACCIDENTAL_CANDIDATES = [-2, -1, 0, 1, 2] as const;

export const MIDI_STATEFUL_PROFILE_ID = "MIDI_STATEFUL_MBC2015_V1" as const;
export const MIDI_CHORD_PROFILE_ID = "MIDI_GENERIC_UPPER_NOTE_DOWNWARD_INTERVALS_V1" as const;

export interface SpelledPitch {
  readonly midiPitch: number;
  readonly step: MusicNoteName;
  readonly accidental: -2 | -1 | 0 | 1 | 2;
  readonly scientificOctave: number;
  readonly display: string;
}

export interface StatefulNoteEvent {
  readonly kind: "note";
  readonly midiPitch: number;
  readonly value: MusicValue;
  readonly augmentationDots?: number;
  readonly tie?: boolean;
  readonly tripletStart?: boolean;
}

export interface StatefulRestEvent {
  readonly kind: "rest";
  readonly value: MusicValue;
  readonly augmentationDots?: number;
  readonly tripletStart?: boolean;
  readonly transcriberAdded?: true;
}

export interface StatefulChordEvent {
  readonly kind: "chord";
  readonly midiPitches: readonly number[];
  readonly value: MusicValue;
  readonly augmentationDots?: number;
  readonly tieAll?: boolean;
  readonly tripletStart?: boolean;
}

export type StatefulLinearMusicEvent =
  | StatefulNoteEvent
  | StatefulRestEvent
  | StatefulChordEvent;

export interface StatefulInAccordAction {
  readonly events:
    readonly StatefulLinearMusicEvent[];
}

export interface StatefulFullMeasureInAccordEvent {
  readonly kind:
    "full-measure-in-accord";
  readonly actions:
    readonly StatefulInAccordAction[];
}

export interface StatefulPartMeasureInAccordEvent {
  readonly kind:
    "part-measure-in-accord";
  readonly actions:
    readonly StatefulInAccordAction[];
}

export type StatefulMusicEvent =
  | StatefulLinearMusicEvent
  | StatefulFullMeasureInAccordEvent
  | StatefulPartMeasureInAccordEvent;

export interface StatefulMeasureInput {
  readonly meter?: Readonly<{
    numerator: number;
    denominator: number;
  }>;
  readonly events: readonly StatefulMusicEvent[];
}

export interface StatefulScoreInput {
  readonly keySharpsFlats?: number;
  readonly meter?: Readonly<{ numerator: number; denominator: number }>;
  readonly measures: readonly StatefulMeasureInput[];
}

export interface StatefulTraceEntry {
  readonly measureIndex: number;
  readonly eventIndex: number;
  readonly kind: StatefulMusicEvent["kind"];
  readonly written?: SpelledPitch;
  readonly members?: readonly SpelledPitch[];
  readonly emittedBrf: string;
}

export interface StatefulScoreEmission extends BrailleEmission {
  readonly profileId: typeof MIDI_STATEFUL_PROFILE_ID;
  readonly chordProfileId: typeof MIDI_CHORD_PROFILE_ID;
  readonly profileDisclosureRequired: true;
  readonly trace: readonly StatefulTraceEntry[];
}

const STEPS = ["C", "D", "E", "F", "G", "A", "B"] as const;
const STEP_PC: Readonly<Record<MusicNoteName, number>> = Object.freeze({
  C: 0, D: 2, E: 4, F: 5, G: 7, A: 9, B: 11,
});

function fail(message: string): never {
  throw new Error(`MUSIC_BRAILLE_STATEFUL_ERROR: ${message}`);
}

function compareTuple(a: readonly number[], b: readonly number[]): number {
  for (let i = 0; i < Math.max(a.length, b.length); i += 1) {
    const av = a[i] ?? 0;
    const bv = b[i] ?? 0;
    if (av !== bv) return av - bv;
  }
  return 0;
}

function keyDefaultAccidental(step: MusicNoteName, sf: number): -1 | 0 | 1 {
  if (sf > 0 && (KEY_SIGNATURE_SHARP_ORDER as readonly string[]).slice(0, sf).includes(step)) return 1;
  if (sf < 0 && (KEY_SIGNATURE_FLAT_ORDER as readonly string[]).slice(0, -sf).includes(step)) return -1;
  return 0;
}

function polarityScore(accidental: number, sf: number): number {
  if (sf < 0) return accidental < 0 ? 0 : accidental === 0 ? 1 : 2;
  return accidental > 0 ? 0 : accidental === 0 ? 1 : 2;
}

function accidentalDisplay(accidental: number): string {
  if (accidental === -2) return "bb";
  if (accidental === -1) return "b";
  if (accidental === 0) return "";
  if (accidental === 1) return "#";
  if (accidental === 2) return "##";
  fail(`unsupported accidental value ${accidental}`);
}

function explicitAccidentalName(accidental: -2 | -1 | 0 | 1 | 2): ExplicitAccidental {
  if (accidental === -2) return "doubleFlat";
  if (accidental === -1) return "flat";
  if (accidental === 0) return "natural";
  if (accidental === 1) return "sharp";
  return "doubleSharp";
}

export function spellMidiPitch(midiPitch: number, keySharpsFlats = 0): SpelledPitch {
  if (!Number.isInteger(midiPitch) || midiPitch < 0 || midiPitch > 127) {
    fail(`MIDI pitch must be an integer in 0..127, got ${midiPitch}`);
  }
  if (!Number.isInteger(keySharpsFlats) || keySharpsFlats < -7 || keySharpsFlats > 7) {
    fail(`keySharpsFlats must be an integer in -7..7, got ${keySharpsFlats}`);
  }

  const pitchClass = midiPitch % 12;
  const candidates: Array<{ score: readonly number[]; pitch: SpelledPitch }> = [];

  for (let stepIndex = 0; stepIndex < STEPS.length; stepIndex += 1) {
    const step = STEPS[stepIndex];
    if (step === undefined) continue;
    for (const accidental of SPELLING_ACCIDENTAL_CANDIDATES) {
      if ((STEP_PC[step] + accidental + 24) % 12 !== pitchClass) continue;
      const octaveRaw = (midiPitch - accidental - STEP_PC[step]) / 12 - 1;
      if (!Number.isInteger(octaveRaw)) continue;
      const scientificOctave = octaveRaw;
      if (scientificOctave < 0 || scientificOctave > 8) continue;

      const keyDefault = keyDefaultAccidental(step, keySharpsFlats);
      const score = [
        Math.abs(accidental - keyDefault),
        polarityScore(accidental, keySharpsFlats),
        Math.abs(accidental),
        stepIndex,
      ] as const;
      candidates.push({
        score,
        pitch: Object.freeze({
          midiPitch,
          step,
          accidental,
          scientificOctave,
          display: `${step}${accidentalDisplay(accidental)}${scientificOctave}`,
        }),
      });
    }
  }

  if (candidates.length === 0) fail(`no representable spelling for MIDI pitch ${midiPitch}`);
  candidates.sort((a, b) => compareTuple(a.score, b.score));
  const winner = candidates[0];
  if (winner === undefined) fail(`no representable spelling for MIDI pitch ${midiPitch}`);
  return winner.pitch;
}

function staffPosition(pitch: SpelledPitch): number {
  return pitch.scientificOctave * 7 + STEPS.indexOf(pitch.step);
}

export function melodicDiatonicInterval(a: SpelledPitch, b: SpelledPitch): number {
  return Math.abs(staffPosition(b) - staffPosition(a)) + 1;
}

export function octaveMarkRequired(previous: SpelledPitch | null, current: SpelledPitch, force = false): boolean {
  if (force || previous === null) return true;
  const interval = melodicDiatonicInterval(previous, current);
  if (interval < 4) return false;
  if (interval > 5) return true;
  return previous.scientificOctave !== current.scientificOctave;
}

class AccidentalState {
  readonly #sf: number;
  readonly #overrides = new Map<string, -2 | -1 | 0 | 1 | 2>();

  constructor(sf: number) {
    this.#sf = sf;
  }

  reset(): void {
    this.#overrides.clear();
  }

  consume(pitch: SpelledPitch): ExplicitAccidental | undefined {
    const key = `${pitch.step}${pitch.scientificOctave}`;
    const current = this.#overrides.get(key) ?? keyDefaultAccidental(pitch.step, this.#sf);
    if (current === pitch.accidental) return undefined;
    this.#overrides.set(key, pitch.accidental);
    return explicitAccidentalName(pitch.accidental);
  }
}

function descendingInterval(written: SpelledPitch, member: SpelledPitch): 2 | 3 | 4 | 5 | 6 | 7 | 8 {
  const difference = staffPosition(written) - staffPosition(member);
  const interval = difference + 1;
  if (!Number.isInteger(interval) || interval < 2 || interval > 8) {
    fail(`UNSUPPORTED_COMPOUND_CHORD_INTERVAL: ${written.display} -> ${member.display} gives interval ${interval}`);
  }
  return interval as 2 | 3 | 4 | 5 | 6 | 7 | 8;
}

function validateKey(sf: number): void {
  if (!Number.isInteger(sf) || sf < -7 || sf > 7) fail(`keySharpsFlats must be an integer in -7..7, got ${sf}`);
}

function freezeTrace(entry: StatefulTraceEntry): StatefulTraceEntry {
  if (entry.members === undefined) {
    return Object.freeze({ ...entry });
  }
  return Object.freeze({
    ...entry,
    members: Object.freeze([...entry.members]),
  });
}

export function encodeStatefulScore(input: StatefulScoreInput): StatefulScoreEmission {
  if (input.measures.length === 0) {
    fail("score requires at least one measure");
  }

  const sf = input.keySharpsFlats ?? 0;
  validateKey(sf);

  let brf = "";
  if (sf !== 0) brf += keySignatureBrf(sf);
  if (input.meter) brf += simpleMeterBrf(input.meter.numerator, input.meter.denominator);
  if (sf !== 0 || input.meter) brf += " ";

  const accidentalState = new AccidentalState(sf);
  const trace: StatefulTraceEntry[] = [];
  let previousWritten: SpelledPitch | null = null;
  let forceNextOctave = true;
  let activeMeter =
    input.meter
    ?? null;

  for (const [measureIndex, measure] of input.measures.entries()) {
    accidentalState.reset();

    if (measure.meter !== undefined) {
      const changed =
        activeMeter === null
        || activeMeter.numerator
          !== measure.meter.numerator
        || activeMeter.denominator
          !== measure.meter.denominator;

      if (changed) {
        brf += simpleMeterBrf(
          measure.meter.numerator,
          measure.meter.denominator,
        );
        brf += " ";
        previousWritten = null;
        forceNextOctave = true;
        activeMeter =
          measure.meter;
      }
    }

    for (const [eventIndex, event] of measure.events.entries()) {
      let emitted = "";

      if (
        event.kind === "full-measure-in-accord"
        || event.kind === "part-measure-in-accord"
      ) {
        if (event.actions.length < 2) {
          fail("in-accord requires at least two actions");
        }

        const keyPrefix =
          sf !== 0
            ? `${keySignatureBrf(sf)} `
            : "";

        const actionBrf:
          string[] = [];

        for (const action of event.actions) {
          if (action.events.length === 0) {
            fail("in-accord action requires at least one event");
          }

          const encoded =
            encodeStatefulScore({
              ...(sf !== 0
                ? { keySharpsFlats: sf }
                : {}),
              measures: [
                {
                  events:
                    action.events,
                },
              ],
            });

          if (
            keyPrefix !== ""
            && !encoded.brf.startsWith(
              keyPrefix,
            )
          ) {
            fail("internal in-accord action key prefix mismatch");
          }

          actionBrf.push(
            keyPrefix === ""
              ? encoded.brf
              : encoded.brf.slice(
                  keyPrefix.length,
                ),
          );
        }

        const inAccordSign =
          event.kind === "full-measure-in-accord"
            ? fullMeasureInAccordBrf()
            : partMeasureInAccordBrf();

        emitted =
          actionBrf.join(
            inAccordSign,
          );

        previousWritten = null;
        forceNextOctave = true;

        trace.push(
          freezeTrace({
            measureIndex,
            eventIndex,
            kind: event.kind,
            emittedBrf: emitted,
          }),
        );
        brf += emitted;
        continue;
      }

      if (event.kind === "rest") {
        emitted = encodeAtomicRest({
          value: event.value,
          ...(event.augmentationDots !== undefined ? { augmentationDots: event.augmentationDots } : {}),
          ...(event.tripletStart !== undefined ? { tripletStart: event.tripletStart } : {}),
        }).brf;

        if (event.transcriberAdded === true) {
          emitted =
            transcriberAddedRestPrefixBrf()
            + emitted;
        }
      } else if (event.kind === "note") {
        const written = spellMidiPitch(event.midiPitch, sf);
        const accidental = accidentalState.consume(written);
        const includeOctave = octaveMarkRequired(previousWritten, written, forceNextOctave);
        emitted = encodeAtomicNote({
          step: written.step,
          scientificOctave: written.scientificOctave,
          value: event.value,
          includeOctave,
          ...(accidental !== undefined ? { accidental } : {}),
          ...(event.augmentationDots !== undefined ? { augmentationDots: event.augmentationDots } : {}),
          ...(event.tie !== undefined ? { tie: event.tie } : {}),
          ...(event.tripletStart !== undefined ? { tripletStart: event.tripletStart } : {}),
        }).brf;
        previousWritten = written;
        forceNextOctave = false;
        trace.push(freezeTrace({ measureIndex, eventIndex, kind: event.kind, written, emittedBrf: emitted }));
        brf += emitted;
        continue;
      } else if (event.kind === "chord") {
        if (event.midiPitches.length < 2) {
          fail("chord requires at least two MIDI pitches");
        }
        const sorted = [...event.midiPitches].sort((a, b) => b - a);
        if (new Set(sorted).size !== sorted.length) {
          fail("DUPLICATE_CHORD_PITCH: same-pitch chord duplicates are unsupported");
        }

        const spelled = sorted.map((midiPitch) => spellMidiPitch(midiPitch, sf));
        const written = spelled[0];
        if (written === undefined) fail("chord requires a written pitch");
        const members = spelled.slice(1);
        const writtenAccidental = accidentalState.consume(written);
        const includeOctave = octaveMarkRequired(previousWritten, written, forceNextOctave);
        const intervals: AtomicChordIntervalInput[] = members.map((member) => {
          const accidental = accidentalState.consume(member);
          return {
            diatonicInterval: descendingInterval(written, member),
            ...(accidental !== undefined ? { accidental } : {}),
          };
        });

        emitted = encodeAtomicChord({
          writtenNote: {
            step: written.step,
            scientificOctave: written.scientificOctave,
            value: event.value,
            includeOctave,
            ...(writtenAccidental !== undefined ? { accidental: writtenAccidental } : {}),
            ...(event.augmentationDots !== undefined ? { augmentationDots: event.augmentationDots } : {}),
            ...(event.tripletStart !== undefined ? { tripletStart: event.tripletStart } : {}),
          },
          intervals,
          ...(event.tieAll !== undefined ? { tieAll: event.tieAll } : {}),
        }).brf;
        previousWritten = written;
        forceNextOctave = false;
        trace.push(freezeTrace({ measureIndex, eventIndex, kind: event.kind, written, members, emittedBrf: emitted }));
        brf += emitted;
        continue;
      } else {
        const exhaustive: never = event;
        fail(`unsupported event ${(exhaustive as { kind?: string }).kind ?? "unknown"}`);
      }

      trace.push(freezeTrace({ measureIndex, eventIndex, kind: event.kind, emittedBrf: emitted }));
      brf += emitted;
    }

    if (measureIndex + 1 < input.measures.length) brf += " ";
  }

  return Object.freeze({
    brf,
    unicode: brfAsciiToUnicode(brf),
    profileId: MIDI_STATEFUL_PROFILE_ID,
    chordProfileId: MIDI_CHORD_PROFILE_ID,
    profileDisclosureRequired: true,
    trace: Object.freeze(trace),
  });
}
