// Generated by Phase 14.6b. Do not hand-edit.
// Stateful MIDI-profile Music Braille encoder.
// PHASE16_PACK_B_MUSICXML: optional validated written-pitch override.
// NotationScore integration remains Phase 14.7.

import { brfAsciiToUnicode } from "./braille-ascii.js";
import {
  encodeAtomicChord,
  encodeAtomicNote,
  encodeAtomicRest,
  fullMeasureInAccordBrf,
  partMeasureInAccordBrf,
  keySignatureBrf,
  simpleMeterBrf,
  transcriberAddedRestPrefixBrf,
  type AtomicChordIntervalInput,
  type BrailleEmission,
  type ExplicitAccidental,
  type MusicNoteName,
  type MusicValue,
} from "./music-braille-atomic-encoder.js";

export const KEY_SIGNATURE_SHARP_ORDER = ["F", "C", "G", "D", "A", "E", "B"] as const;
export const KEY_SIGNATURE_FLAT_ORDER = ["B", "E", "A", "D", "G", "C", "F"] as const;
export const SPELLING_ACCIDENTAL_CANDIDATES = [-2, -1, 0, 1, 2] as const;

export const MIDI_STATEFUL_PROFILE_ID = "MIDI_STATEFUL_MBC2015_V1" as const;
export const MIDI_CHORD_PROFILE_ID = "MIDI_GENERIC_UPPER_NOTE_DOWNWARD_INTERVALS_V1" as const;
export const KEYBOARD_DIRECTIONAL_CHORD_PROFILE_ID = "MBC2015_KEYBOARD_RH_DOWN_LH_UP_V1" as const;

export interface SpelledPitch {
  readonly midiPitch: number;
  readonly step: MusicNoteName;
  readonly accidental: -2 | -1 | 0 | 1 | 2;
  readonly scientificOctave: number;
  readonly display: string;
}

export interface StatefulWrittenPitch {
  readonly step: MusicNoteName;
  readonly accidental: -2 | -1 | 0 | 1 | 2;
  readonly scientificOctave: number;
}

export type StatefulArticulation =
  | "staccato"
  | "staccatissimo"
  | "accent"
  | "tenuto";

export const STATEFUL_ARTICULATION_BRF = Object.freeze({
  staccato: "8",
  staccatissimo: ",8",
  accent: ".8",
  tenuto: "_8",
} as const);

export type StatefulGrace =
  | "short"
  | "long";

export const STATEFUL_GRACE_BRF = Object.freeze({
  short: "5",
  long: "\"5",
} as const);

export type StatefulDynamic =
  | "pp"
  | "p"
  | "mp"
  | "mf"
  | "f"
  | "ff"
  | "fff"
  | "sf"
  | "sfz";

export const STATEFUL_DYNAMIC_BRF = Object.freeze({
  pp: ">pp",
  p: ">p",
  mp: ">mp",
  mf: ">mf",
  f: ">f",
  ff: ">ff",
  fff: ">fff",
  sf: ">sf",
  sfz: ">sfz",
} as const);

export const STATEFUL_SIMPLE_SLUR_BRF = "c" as const;

// PHASE16_R5_BANA_LONGER_SLUR
// Backward-compatible slur suffix multiplicity:
// - true = one BANA single-slur cell
// - 2    = doubled single-slur after the first event of a >4-note phrase
export type StatefulSlurAfter = true | 2;
export const STATEFUL_INITIAL_REPEAT_BRF = "<7" as const;
export const STATEFUL_TERMINAL_REPEAT_BRF = "<2" as const;
export const STATEFUL_VOLTA_BRF = Object.freeze({
  1: "#1",
  2: "#2",
} as const);

export type StatefulWordExpressionPolicy =
  | "word-expression"
  | "canonical-word-expression"
  | "bana-word-expression-fallback"
  | "music-metronome-expression";

export interface StatefulWordExpression {
  readonly sourceText: string;
  readonly normalizedText: string;
  readonly brfText: string;
  readonly categories: readonly string[];
  readonly semanticTags: readonly string[];
  readonly canonicalTerms: readonly string[];
  readonly policy: StatefulWordExpressionPolicy;
}

export interface StatefulNoteEvent {
  readonly kind: "note";
  readonly midiPitch: number;
  readonly writtenPitch?: StatefulWrittenPitch;
  readonly value: MusicValue;
  readonly augmentationDots?: number;
  readonly tie?: boolean;
  readonly tripletStart?: boolean;
  readonly articulations?: readonly StatefulArticulation[];
  readonly grace?: StatefulGrace;
  readonly dynamic?: StatefulDynamic;
  readonly wordExpressions?: readonly StatefulWordExpression[];
  readonly slurAfter?: StatefulSlurAfter;
  // PHASE16_R7_DIRECTION_MARKS
  readonly pedalDown?: true;
  readonly pedalUp?: true;
  readonly hairpinStart?: "crescendo" | "diminuendo";
  readonly hairpinStop?: "crescendo" | "diminuendo";
}

export interface StatefulRestEvent {
  readonly kind: "rest";
  readonly value: MusicValue;
  readonly augmentationDots?: number;
  readonly tripletStart?: boolean;
  readonly transcriberAdded?: true;
  readonly dynamic?: StatefulDynamic;
  readonly wordExpressions?: readonly StatefulWordExpression[];
  readonly slurAfter?: StatefulSlurAfter;
  // PHASE16_R7_DIRECTION_MARKS
  readonly pedalDown?: true;
  readonly pedalUp?: true;
  readonly hairpinStart?: "crescendo" | "diminuendo";
  readonly hairpinStop?: "crescendo" | "diminuendo";
}

export interface StatefulChordEvent {
  readonly kind: "chord";
  readonly midiPitches: readonly number[];
  readonly writtenPitches?: readonly StatefulWrittenPitch[];
  readonly value: MusicValue;
  readonly augmentationDots?: number;
  readonly tieAll?: boolean;
  // PHASE16_R8_SINGLE_MEMBER_CHORD_TIE
  readonly singleTieMidiPitch?: number;
  readonly tripletStart?: boolean;
  readonly articulations?: readonly StatefulArticulation[];
  readonly grace?: StatefulGrace;
  readonly dynamic?: StatefulDynamic;
  readonly wordExpressions?: readonly StatefulWordExpression[];
  readonly slurAfter?: StatefulSlurAfter;
  // PHASE16_R7_DIRECTION_MARKS
  readonly pedalDown?: true;
  readonly pedalUp?: true;
  readonly hairpinStart?: "crescendo" | "diminuendo";
  readonly hairpinStop?: "crescendo" | "diminuendo";
}

export type StatefulLinearMusicEvent =
  | StatefulNoteEvent
  | StatefulRestEvent
  | StatefulChordEvent;

export interface StatefulInAccordAction {
  readonly events:
    readonly StatefulLinearMusicEvent[];
}

export interface StatefulFullMeasureInAccordEvent {
  readonly kind:
    "full-measure-in-accord";
  readonly actions:
    readonly StatefulInAccordAction[];
  readonly wordExpressions?: readonly StatefulWordExpression[];
}

export interface StatefulPartMeasureInAccordEvent {
  readonly kind:
    "part-measure-in-accord";
  readonly actions:
    readonly StatefulInAccordAction[];
  readonly wordExpressions?: readonly StatefulWordExpression[];
}

export interface StatefulKeyboardParallelEvent {
  readonly kind: "keyboard-parallel";
  readonly rightActions: readonly StatefulInAccordAction[];
  readonly leftActions: readonly StatefulInAccordAction[];
  readonly wordExpressions?: readonly StatefulWordExpression[];
}

export type StatefulMusicEvent =
  | StatefulLinearMusicEvent
  | StatefulFullMeasureInAccordEvent
  | StatefulPartMeasureInAccordEvent
  | StatefulKeyboardParallelEvent;

export interface StatefulMeasureInput {
  readonly keySharpsFlats?: number;
  readonly meter?: Readonly<{
    numerator: number;
    denominator: number;
  }>;
  readonly initialRepeat?: true;
  readonly terminalRepeat?: true;
  readonly volta?: 1 | 2;
  readonly events: readonly StatefulMusicEvent[];
}

export interface StatefulScoreInput {
  readonly keySharpsFlats?: number;
  readonly meter?: Readonly<{ numerator: number; denominator: number }>;
  readonly intervalDirection?: "down" | "up";
  readonly measures: readonly StatefulMeasureInput[];
}

export interface StatefulTraceEntry {
  readonly measureIndex: number;
  readonly eventIndex: number;
  readonly kind: StatefulMusicEvent["kind"];
  readonly written?: SpelledPitch;
  readonly members?: readonly SpelledPitch[];
  readonly emittedBrf: string;
}

export interface StatefulScoreEmission extends BrailleEmission {
  readonly profileId: typeof MIDI_STATEFUL_PROFILE_ID;
  readonly chordProfileId: typeof MIDI_CHORD_PROFILE_ID;
  readonly keyboardChordProfileId?: typeof KEYBOARD_DIRECTIONAL_CHORD_PROFILE_ID;
  readonly profileDisclosureRequired: true;
  readonly trace: readonly StatefulTraceEntry[];
}

const STEPS = ["C", "D", "E", "F", "G", "A", "B"] as const;
const STEP_PC: Readonly<Record<MusicNoteName, number>> = Object.freeze({
  C: 0, D: 2, E: 4, F: 5, G: 7, A: 9, B: 11,
});

function fail(message: string): never {
  throw new Error(`MUSIC_BRAILLE_STATEFUL_ERROR: ${message}`);
}

function compareTuple(a: readonly number[], b: readonly number[]): number {
  for (let i = 0; i < Math.max(a.length, b.length); i += 1) {
    const av = a[i] ?? 0;
    const bv = b[i] ?? 0;
    if (av !== bv) return av - bv;
  }
  return 0;
}

function keyDefaultAccidental(step: MusicNoteName, sf: number): -1 | 0 | 1 {
  if (sf > 0 && (KEY_SIGNATURE_SHARP_ORDER as readonly string[]).slice(0, sf).includes(step)) return 1;
  if (sf < 0 && (KEY_SIGNATURE_FLAT_ORDER as readonly string[]).slice(0, -sf).includes(step)) return -1;
  return 0;
}

function polarityScore(accidental: number, sf: number): number {
  if (sf < 0) return accidental < 0 ? 0 : accidental === 0 ? 1 : 2;
  return accidental > 0 ? 0 : accidental === 0 ? 1 : 2;
}

function accidentalDisplay(accidental: number): string {
  if (accidental === -2) return "bb";
  if (accidental === -1) return "b";
  if (accidental === 0) return "";
  if (accidental === 1) return "#";
  if (accidental === 2) return "##";
  fail(`unsupported accidental value ${accidental}`);
}

function explicitAccidentalName(accidental: -2 | -1 | 0 | 1 | 2): ExplicitAccidental {
  if (accidental === -2) return "doubleFlat";
  if (accidental === -1) return "flat";
  if (accidental === 0) return "natural";
  if (accidental === 1) return "sharp";
  return "doubleSharp";
}


function articulationPrefixBrf(
  articulations: readonly StatefulArticulation[] | undefined,
): string {
  if (articulations === undefined || articulations.length === 0) return "";

  if (articulations.length !== 1) {
    fail(
      "PHASE16_5D3_MULTI_ARTICULATION_DEFERRED: "
      + "the initial BANA-backed MusicXML articulation bridge accepts exactly one explicit articulation per note/chord.",
    );
  }

  const articulation = articulations[0];
  if (articulation === undefined) return "";

  const token = STATEFUL_ARTICULATION_BRF[articulation];
  if (typeof token !== "string") {
    fail(`unsupported articulation ${String(articulation)}`);
  }

  return token;
}

function gracePrefixBrf(grace: StatefulGrace | undefined): string {
  if (grace === undefined) return "";
  return STATEFUL_GRACE_BRF[grace];
}

// PHASE16_R7_DIRECTION_MARKS
// BANA MBC 2015:
// - Table 25 / 29.10: pedal down <c, pedal up *c.
// - Table 22(C) / 22.3.3: diverging >c ... >3,
//   converging >d ... >4.
export const STATEFUL_PEDAL_DOWN_BRF = "<c" as const;
export const STATEFUL_PEDAL_UP_BRF = "*c" as const;

export const STATEFUL_HAIRPIN_START_BRF =
  Object.freeze({
    crescendo: ">c",
    diminuendo: ">d",
  } as const);

export const STATEFUL_HAIRPIN_STOP_BRF =
  Object.freeze({
    crescendo: ">3",
    diminuendo: ">4",
  } as const);

function directionMarkPrefixBrf(
  event: Readonly<{
    pedalDown?: true;
    hairpinStart?: "crescendo" | "diminuendo";
  }>,
): string {
  return (
    (event.pedalDown === true
      ? STATEFUL_PEDAL_DOWN_BRF
      : "")
    + (
      event.hairpinStart !== undefined
        ? STATEFUL_HAIRPIN_START_BRF[
            event.hairpinStart
          ]
        : ""
    )
  );
}

function directionMarkSuffixBrf(
  event: Readonly<{
    pedalUp?: true;
    hairpinStop?: "crescendo" | "diminuendo";
  }>,
): string {
  // Both signs are post-note signs in the admitted BANA profile.
  // When both coincide, Braille Hub uses stable hairpin-terminator
  // then pedal-up ordering as an explicit transcriber policy.
  return (
    (
      event.hairpinStop !== undefined
        ? STATEFUL_HAIRPIN_STOP_BRF[
            event.hairpinStop
          ]
        : ""
    )
    + (
      event.pedalUp === true
        ? STATEFUL_PEDAL_UP_BRF
        : ""
    )
  );
}

function simpleSlurSuffixBrf(
  slurAfter: StatefulSlurAfter | undefined,
): string {
  const count =
    slurAfter === true
      ? 1
      : (slurAfter ?? 0);

  return STATEFUL_SIMPLE_SLUR_BRF.repeat(count);
}

function firstBrailleCellContainsDots123(brf: string): boolean {
  if (brf.length === 0) return false;
  const unicode = brfAsciiToUnicode(brf[0]!);
  const codePoint = unicode.codePointAt(0);
  if (codePoint === undefined || codePoint < 0x2800 || codePoint > 0x28ff) {
    fail(`cannot inspect Braille dots for BRF cell ${JSON.stringify(brf[0])}`);
  }
  const dots = codePoint - 0x2800;
  return (dots & 0b00000111) !== 0;
}

function dynamicPrefixBrf(
  dynamic: StatefulDynamic | undefined,
  followingBrf: string,
): string {
  if (dynamic === undefined) return "";
  const base = STATEFUL_DYNAMIC_BRF[dynamic];
  return firstBrailleCellContainsDots123(followingBrf)
    ? `${base}'`
    : base;
}

const STATEFUL_WORD_SIGN_BRF = ">" as const;
const STATEFUL_WORD_DOT3_BRF = "'" as const;

function validateWordExpressionBrfText(
  expression: StatefulWordExpression,
): string {
  const value = expression.brfText.trim().toLowerCase();

  if (value === "") {
    fail("PHASE16_R2B_EMPTY_WORD_EXPRESSION");
  }

  if (!/^[a-z. ]+$/.test(value)) {
    fail(
      "PHASE16_R2B_WORD_TEXT_DEFERRED: "
      + `unsupported literary text ${JSON.stringify(expression.brfText)}`,
    );
  }

  return value;
}

function singleWordExpressionBrf(
  expression: StatefulWordExpression,
): string {
  // PHASE16_R4_SIMPLE_METRONOME
  // BANA MBC 2015 1.8 / 1.8.1:
  //   indefinite-pitch C in the required value + 7 + one numeric indicator,
  //   enclosed in music parentheses when embedded in a music line.
  // Raw BRF is accepted only for the bridge-generated bounded contract.
  if (expression.policy === "music-metronome-expression") {
    const value = expression.brfText.trim();
    if (!/^,'(?:\?|D)7#[a-j]+,'$/.test(value)) {
      fail(
        "PHASE16_R4_INVALID_METRONOME_BRF: "
        + JSON.stringify(expression.brfText),
      );
    }
    // Section 1.8.1 treats the marking like a key/time change: between spaces.
    return ` ${value} `;
  }
  const value = validateWordExpressionBrfText(expression);
  const literary =
    value.replace(/\./g, STATEFUL_WORD_DOT3_BRF);

  if (value.includes(" ")) {
    return `${STATEFUL_WORD_SIGN_BRF}${literary}${STATEFUL_WORD_SIGN_BRF} `;
  }

  return `${STATEFUL_WORD_SIGN_BRF}${literary}`;
}

function wordExpressionPrefixBrf(
  expressions: readonly StatefulWordExpression[] | undefined,
  followingBrf: string,
): string {
  if (expressions === undefined || expressions.length === 0) {
    return "";
  }

  const encoded = expressions.map(singleWordExpressionBrf);
  let result = encoded.join("");

  const finalSource =
    expressions[expressions.length - 1];
  const finalIsMetronome =
    finalSource?.policy === "music-metronome-expression";

  const finalText =
    finalSource === undefined || finalIsMetronome
      ? ""
      : validateWordExpressionBrfText(finalSource);

  const finalIsLong = finalText.includes(" ");
  const finalHasPrintPeriod = finalText.endsWith(".");

  if (
    !finalIsMetronome
    && !finalIsLong
    && !finalHasPrintPeriod
    && firstBrailleCellContainsDots123(followingBrf)
  ) {
    result += STATEFUL_WORD_DOT3_BRF;
  }

  return result;
}

function voltaPrefixBrf(volta: 1 | 2 | undefined): string {
  if (volta === undefined) return "";
  return STATEFUL_VOLTA_BRF[volta];
}

export function spellMidiPitch(midiPitch: number, keySharpsFlats = 0): SpelledPitch {
  if (!Number.isInteger(midiPitch) || midiPitch < 0 || midiPitch > 127) {
    fail(`MIDI pitch must be an integer in 0..127, got ${midiPitch}`);
  }
  if (!Number.isInteger(keySharpsFlats) || keySharpsFlats < -7 || keySharpsFlats > 7) {
    fail(`keySharpsFlats must be an integer in -7..7, got ${keySharpsFlats}`);
  }

  const pitchClass = midiPitch % 12;
  const candidates: Array<{ score: readonly number[]; pitch: SpelledPitch }> = [];

  for (let stepIndex = 0; stepIndex < STEPS.length; stepIndex += 1) {
    const step = STEPS[stepIndex];
    if (step === undefined) continue;
    for (const accidental of SPELLING_ACCIDENTAL_CANDIDATES) {
      if ((STEP_PC[step] + accidental + 24) % 12 !== pitchClass) continue;
      const octaveRaw = (midiPitch - accidental - STEP_PC[step]) / 12 - 1;
      if (!Number.isInteger(octaveRaw)) continue;
      const scientificOctave = octaveRaw;
      if (scientificOctave < 0 || scientificOctave > 8) continue;

      const keyDefault = keyDefaultAccidental(step, keySharpsFlats);
      const score = [
        Math.abs(accidental - keyDefault),
        polarityScore(accidental, keySharpsFlats),
        Math.abs(accidental),
        stepIndex,
      ] as const;
      candidates.push({
        score,
        pitch: Object.freeze({
          midiPitch,
          step,
          accidental,
          scientificOctave,
          display: `${step}${accidentalDisplay(accidental)}${scientificOctave}`,
        }),
      });
    }
  }

  if (candidates.length === 0) fail(`no representable spelling for MIDI pitch ${midiPitch}`);
  candidates.sort((a, b) => compareTuple(a.score, b.score));
  const winner = candidates[0];
  if (winner === undefined) fail(`no representable spelling for MIDI pitch ${midiPitch}`);
  return winner.pitch;
}

function staffPosition(pitch: SpelledPitch): number {
  return pitch.scientificOctave * 7 + STEPS.indexOf(pitch.step);
}

export function melodicDiatonicInterval(a: SpelledPitch, b: SpelledPitch): number {
  return Math.abs(staffPosition(b) - staffPosition(a)) + 1;
}

export function octaveMarkRequired(previous: SpelledPitch | null, current: SpelledPitch, force = false): boolean {
  if (force || previous === null) return true;
  const interval = melodicDiatonicInterval(previous, current);
  if (interval < 4) return false;
  if (interval > 5) return true;
  return previous.scientificOctave !== current.scientificOctave;
}

function spelledFromWrittenPitch(
  written: StatefulWrittenPitch,
  midiPitch: number,
): SpelledPitch {
  if (!(STEPS as readonly string[]).includes(written.step)) {
    fail(`unsupported written step ${String(written.step)}`);
  }
  if (!Number.isInteger(written.accidental) || written.accidental < -2 || written.accidental > 2) {
    fail(`written accidental must be an integer in -2..2, got ${written.accidental}`);
  }
  if (!Number.isInteger(written.scientificOctave) || written.scientificOctave < 0 || written.scientificOctave > 8) {
    fail(`written octave must be an integer in 0..8, got ${written.scientificOctave}`);
  }
  const expectedMidi =
    (written.scientificOctave + 1) * 12
    + STEP_PC[written.step]
    + written.accidental;
  if (expectedMidi !== midiPitch) {
    fail(
      `WRITTEN_PITCH_MIDI_MISMATCH: ${written.step}${accidentalDisplay(written.accidental)}${written.scientificOctave} maps to MIDI ${expectedMidi}, got ${midiPitch}`,
    );
  }
  return Object.freeze({
    midiPitch,
    step: written.step,
    accidental: written.accidental,
    scientificOctave: written.scientificOctave,
    display: `${written.step}${accidentalDisplay(written.accidental)}${written.scientificOctave}`,
  });
}

class AccidentalState {
  readonly #sf: number;
  readonly #overrides = new Map<string, -2 | -1 | 0 | 1 | 2>();

  constructor(sf: number) {
    this.#sf = sf;
  }

  reset(): void {
    this.#overrides.clear();
  }

  consume(pitch: SpelledPitch): ExplicitAccidental | undefined {
    const key = `${pitch.step}${pitch.scientificOctave}`;
    const current = this.#overrides.get(key) ?? keyDefaultAccidental(pitch.step, this.#sf);
    if (current === pitch.accidental) return undefined;
    this.#overrides.set(key, pitch.accidental);
    return explicitAccidentalName(pitch.accidental);
  }
}

function descendingInterval(written: SpelledPitch, member: SpelledPitch): 2 | 3 | 4 | 5 | 6 | 7 | 8 {
  const difference = staffPosition(written) - staffPosition(member);
  const interval = difference + 1;
  if (!Number.isInteger(interval) || interval < 2 || interval > 8) {
    fail(`UNSUPPORTED_COMPOUND_CHORD_INTERVAL: ${written.display} -> ${member.display} gives interval ${interval}`);
  }
  return interval as 2 | 3 | 4 | 5 | 6 | 7 | 8;
}

function ascendingInterval(written: SpelledPitch, member: SpelledPitch): 2 | 3 | 4 | 5 | 6 | 7 | 8 {
  const difference = staffPosition(member) - staffPosition(written);
  const interval = difference + 1;
  if (!Number.isInteger(interval) || interval < 2 || interval > 8) {
    fail(`UNSUPPORTED_COMPOUND_CHORD_INTERVAL: ${written.display} -> ${member.display} gives interval ${interval}`);
  }
  return interval as 2 | 3 | 4 | 5 | 6 | 7 | 8;
}

function keyboardHandSignBrf(hand: "right" | "left"): string {
  return hand === "right" ? ".>" : "_>";
}

function validateKey(sf: number): void {
  if (!Number.isInteger(sf) || sf < -7 || sf > 7) fail(`keySharpsFlats must be an integer in -7..7, got ${sf}`);
}

function freezeTrace(entry: StatefulTraceEntry): StatefulTraceEntry {
  if (entry.members === undefined) {
    return Object.freeze({ ...entry });
  }
  return Object.freeze({
    ...entry,
    members: Object.freeze([...entry.members]),
  });
}

export function encodeStatefulScore(input: StatefulScoreInput): StatefulScoreEmission {
  if (input.measures.length === 0) {
    fail("score requires at least one measure");
  }

  const initialSf = input.keySharpsFlats ?? 0;
  validateKey(initialSf);

  const intervalDirection = input.intervalDirection ?? "down";
  let keyboardDirectionalProfileUsed = false;
  let activeSf = initialSf;
  let brf = "";
  if (activeSf !== 0) brf += keySignatureBrf(activeSf);
  if (input.meter) brf += simpleMeterBrf(input.meter.numerator, input.meter.denominator);
  if (activeSf !== 0 || input.meter) brf += " ";

  let accidentalState = new AccidentalState(activeSf);
  const trace: StatefulTraceEntry[] = [];
  let previousWritten: SpelledPitch | null = null;
  let forceNextOctave = true;
  let activeMeter = input.meter ?? null;

  for (const [measureIndex, measure] of input.measures.entries()) {
    const requestedSf = measure.keySharpsFlats;
    if (requestedSf !== undefined) validateKey(requestedSf);

    const keyChanged =
      requestedSf !== undefined
      && requestedSf !== activeSf;
    const meterChanged =
      measure.meter !== undefined
      && (
        activeMeter === null
        || activeMeter.numerator !== measure.meter.numerator
        || activeMeter.denominator !== measure.meter.denominator
      );

    if (keyChanged && requestedSf === 0 && activeSf !== 0) {
      fail(
        "PHASE16_5_KEY_CANCELLATION_DEFERRED: "
        + "transition to a zero-signature key requires an explicit cancellation contract.",
      );
    }

    let boundarySignature = "";
    if (keyChanged) {
      boundarySignature += keySignatureBrf(requestedSf!);
      activeSf = requestedSf!;
    }
    if (meterChanged) {
      boundarySignature += simpleMeterBrf(
        measure.meter!.numerator,
        measure.meter!.denominator,
      );
      activeMeter = measure.meter!;
    }
    if (boundarySignature !== "") {
      brf += boundarySignature + " ";
      previousWritten = null;
      forceNextOctave = true;
    }

    accidentalState = new AccidentalState(activeSf);
    accidentalState.reset();

    if (measure.initialRepeat === true && measure.volta !== undefined) {
      fail("initial repeat and volta prefix are not combined by the frozen Phase 16.5 profile");
    }

    if (measure.volta !== undefined) {
      brf += voltaPrefixBrf(measure.volta);
      previousWritten = null;
      forceNextOctave = true;
    }
    if (measure.initialRepeat === true) {
      brf += STATEFUL_INITIAL_REPEAT_BRF;
    }

    for (const [eventIndex, event] of measure.events.entries()) {
      let emitted = "";

      if (event.kind === "keyboard-parallel") {
        keyboardDirectionalProfileUsed = true;

        const keyPrefix =
          activeSf !== 0
            ? `${keySignatureBrf(activeSf)} `
            : "";

        const encodeHand = (
          hand: "right" | "left",
          actions: readonly StatefulInAccordAction[],
          direction: "down" | "up",
        ): string => {
          if (actions.length === 0) {
            fail(`keyboard ${hand} hand requires at least one action`);
          }

          const actionBrf: string[] = [];

          for (const action of actions) {
            if (action.events.length === 0) {
              fail(`keyboard ${hand} hand action requires at least one event`);
            }

            const encoded =
              encodeStatefulScore({
                ...(activeSf !== 0
                  ? { keySharpsFlats: activeSf }
                  : {}),
                intervalDirection: direction,
                measures: [
                  {
                    events: action.events,
                  },
                ],
              });

            if (
              keyPrefix !== ""
              && !encoded.brf.startsWith(keyPrefix)
            ) {
              fail(`internal keyboard ${hand} key-prefix mismatch`);
            }

            actionBrf.push(
              keyPrefix === ""
                ? encoded.brf
                : encoded.brf.slice(keyPrefix.length),
            );
          }

          const body =
            actionBrf.length === 1
              ? actionBrf[0]!
              : actionBrf.join(fullMeasureInAccordBrf());

          return keyboardHandSignBrf(hand) + body;
        };

        const rightBrf =
          encodeHand("right", event.rightActions, "down");
        const leftBrf =
          encodeHand("left", event.leftActions, "up");

        emitted =
          wordExpressionPrefixBrf(
            event.wordExpressions,
            rightBrf,
          )
          + rightBrf
          + "\n"
          + leftBrf;

        previousWritten = null;
        forceNextOctave = true;

        trace.push(
          freezeTrace({
            measureIndex,
            eventIndex,
            kind: event.kind,
            emittedBrf: emitted,
          }),
        );
        brf += emitted;
        continue;
      }

      if (
        event.kind === "full-measure-in-accord"
        || event.kind === "part-measure-in-accord"
      ) {
        if (event.actions.length < 2) {
          fail("in-accord requires at least two actions");
        }

        const keyPrefix =
          activeSf !== 0
            ? `${keySignatureBrf(activeSf)} `
            : "";

        const actionBrf: string[] = [];

        for (const action of event.actions) {
          if (action.events.length === 0) {
            fail("in-accord action requires at least one event");
          }

          const encoded =
            encodeStatefulScore({
              ...(activeSf !== 0
                ? { keySharpsFlats: activeSf }
                : {}),
              intervalDirection,
              measures: [
                {
                  events: action.events,
                },
              ],
            });

          if (
            keyPrefix !== ""
            && !encoded.brf.startsWith(keyPrefix)
          ) {
            fail("internal in-accord action key prefix mismatch");
          }

          actionBrf.push(
            keyPrefix === ""
              ? encoded.brf
              : encoded.brf.slice(keyPrefix.length),
          );
        }

        const inAccordSign =
          event.kind === "full-measure-in-accord"
            ? fullMeasureInAccordBrf()
            : partMeasureInAccordBrf();

        emitted = actionBrf.join(inAccordSign);
        emitted =
          wordExpressionPrefixBrf(
            event.wordExpressions,
            emitted,
          )
          + emitted;

        previousWritten = null;
        forceNextOctave = true;

        trace.push(
          freezeTrace({
            measureIndex,
            eventIndex,
            kind: event.kind,
            emittedBrf: emitted,
          }),
        );
        brf += emitted;
        continue;
      }

      if (event.kind === "rest") {
        emitted = encodeAtomicRest({
          value: event.value,
          ...(event.augmentationDots !== undefined ? { augmentationDots: event.augmentationDots } : {}),
          ...(event.tripletStart !== undefined ? { tripletStart: event.tripletStart } : {}),
        }).brf;

        // PHASE16_R3_V6_REST_DYNAMIC
        if (event.transcriberAdded === true) {
          emitted = transcriberAddedRestPrefixBrf() + emitted;
        }

        const restDynamicBrf =
          dynamicPrefixBrf(
            event.dynamic,
            emitted,
          );

        emitted =
          directionMarkPrefixBrf(event)
          + wordExpressionPrefixBrf(
            event.wordExpressions,
            restDynamicBrf + emitted,
          )
          + restDynamicBrf
          + emitted
          + simpleSlurSuffixBrf(event.slurAfter)
          + directionMarkSuffixBrf(event);

        if (
          event.dynamic !== undefined
          || (event.wordExpressions?.length ?? 0) > 0
          || event.hairpinStart !== undefined
          || event.hairpinStop !== undefined
        ) {
          forceNextOctave = true;
        }
      } else if (event.kind === "note") {
        // PHASE16_R9_GRACE_DYNAMIC
        if (
          event.grace !== undefined
          && (
            (event.wordExpressions?.length ?? 0) > 0
            || (event.articulations?.length ?? 0) > 0
            || event.hairpinStart !== undefined
            || event.hairpinStop !== undefined
          )
        ) {
          fail("grace combined with word expressions, articulations, or direction-mark collisions remains deferred");
        }

        if (
          event.dynamic !== undefined
          || (event.wordExpressions?.length ?? 0) > 0
          || event.hairpinStart !== undefined
        ) {
          forceNextOctave = true;
        }

        const written =
          event.writtenPitch !== undefined
            ? spelledFromWrittenPitch(event.writtenPitch, event.midiPitch)
            : spellMidiPitch(event.midiPitch, activeSf);
        const accidental = accidentalState.consume(written);
        const includeOctave = octaveMarkRequired(
          previousWritten,
          written,
          forceNextOctave,
        );

        const core =
          gracePrefixBrf(event.grace)
          + articulationPrefixBrf(event.articulations)
          + encodeAtomicNote({
              step: written.step,
              scientificOctave: written.scientificOctave,
              value: event.value,
              includeOctave,
              ...(accidental !== undefined ? { accidental } : {}),
              ...(event.augmentationDots !== undefined ? { augmentationDots: event.augmentationDots } : {}),
              ...(event.tie !== undefined ? { tie: event.tie } : {}),
              ...(event.tripletStart !== undefined ? { tripletStart: event.tripletStart } : {}),
            }).brf;

        const dynamicBrf =
          dynamicPrefixBrf(event.dynamic, core);

        emitted =
          directionMarkPrefixBrf(event)
          + wordExpressionPrefixBrf(
            event.wordExpressions,
            dynamicBrf + core,
          )
          + dynamicBrf
          + core
          + simpleSlurSuffixBrf(event.slurAfter)
          + directionMarkSuffixBrf(event);

        previousWritten = written;
        forceNextOctave =
          event.hairpinStop !== undefined;
        trace.push(
          freezeTrace({
            measureIndex,
            eventIndex,
            kind: event.kind,
            written,
            emittedBrf: emitted,
          }),
        );
        brf += emitted;
        continue;
      } else if (event.kind === "chord") {
        if (
          event.grace !== undefined
          && (
            event.dynamic !== undefined
            || (event.wordExpressions?.length ?? 0) > 0
            || (event.articulations?.length ?? 0) > 0
            || event.hairpinStart !== undefined
            || event.hairpinStop !== undefined
          )
        ) {
          fail("grace chord combined with dynamics/articulation is deferred in Phase 16.5");
        }

        if (
          event.dynamic !== undefined
          || (event.wordExpressions?.length ?? 0) > 0
          || event.hairpinStart !== undefined
        ) {
          forceNextOctave = true;
        }

        if (event.midiPitches.length < 2) {
          fail("chord requires at least two MIDI pitches");
        }
        if (new Set(event.midiPitches).size !== event.midiPitches.length) {
          fail("DUPLICATE_CHORD_PITCH: same-pitch chord duplicates are unsupported");
        }

        let spelled: SpelledPitch[];
        if (event.writtenPitches !== undefined) {
          if (event.writtenPitches.length !== event.midiPitches.length) {
            fail("WRITTEN_CHORD_PITCH_COUNT_MISMATCH");
          }
          spelled = event.midiPitches.map((midiPitch, index) => {
            const writtenPitch = event.writtenPitches![index];
            if (writtenPitch === undefined) fail("WRITTEN_CHORD_PITCH_COUNT_MISMATCH");
            return spelledFromWrittenPitch(writtenPitch, midiPitch);
          }).sort(
            (a, b) =>
              intervalDirection === "down"
                ? staffPosition(b) - staffPosition(a)
                  || b.midiPitch - a.midiPitch
                : staffPosition(a) - staffPosition(b)
                  || a.midiPitch - b.midiPitch,
          );
        } else {
          const sorted = [...event.midiPitches].sort(
            intervalDirection === "down"
              ? (a, b) => b - a
              : (a, b) => a - b,
          );
          spelled = sorted.map((midiPitch) => spellMidiPitch(midiPitch, activeSf));
        }

        const written = spelled[0];
        if (written === undefined) fail("chord requires a written pitch");
        const members = spelled.slice(1);
        const writtenAccidental = accidentalState.consume(written);
        const includeOctave = octaveMarkRequired(
          previousWritten,
          written,
          forceNextOctave,
        );
        const intervals: AtomicChordIntervalInput[] = members.map((member) => {
          const accidental = accidentalState.consume(member);
          return {
            diatonicInterval:
              intervalDirection === "down"
                ? descendingInterval(written, member)
                : ascendingInterval(written, member),
            ...(accidental !== undefined ? { accidental } : {}),
          };
        });

        // PHASE16_R8_SINGLE_MEMBER_CHORD_TIE
        const atomicWrittenNote =
          Object.freeze({
            step: written.step,
            scientificOctave: written.scientificOctave,
            value: event.value,
            includeOctave,
            ...(writtenAccidental !== undefined
              ? { accidental: writtenAccidental }
              : {}),
            ...(event.augmentationDots !== undefined
              ? { augmentationDots: event.augmentationDots }
              : {}),
            ...(event.tripletStart !== undefined
              ? { tripletStart: event.tripletStart }
              : {}),
          });

        let chordBrf =
          encodeAtomicChord({
            writtenNote: atomicWrittenNote,
            intervals,
            ...(event.tieAll !== undefined
              ? { tieAll: event.tieAll }
              : {}),
          }).brf;

        if (event.singleTieMidiPitch !== undefined) {
          if (event.tieAll === true) {
            fail(
              "singleTieMidiPitch and tieAll are mutually exclusive",
            );
          }

          const writtenNoteBrf =
            encodeAtomicNote(
              atomicWrittenNote,
            ).brf;

          const tiedWrittenNoteBrf =
            encodeAtomicNote({
              ...atomicWrittenNote,
              tie: true,
            }).brf;

          if (
            !tiedWrittenNoteBrf.startsWith(
              writtenNoteBrf,
            )
          ) {
            fail(
              "atomic single-tie derivation is not suffix-compatible",
            );
          }

          const singleTieBrf =
            tiedWrittenNoteBrf.slice(
              writtenNoteBrf.length,
            );

          if (singleTieBrf.length === 0) {
            fail(
              "atomic single-tie derivation produced an empty suffix",
            );
          }

          if (
            written.midiPitch
              === event.singleTieMidiPitch
          ) {
            if (
              !chordBrf.startsWith(
                writtenNoteBrf,
              )
            ) {
              fail(
                "atomic chord does not begin with its written-note encoding",
              );
            }

            chordBrf =
              writtenNoteBrf
              + singleTieBrf
              + chordBrf.slice(
                  writtenNoteBrf.length,
                );
          }
          else {
            const targetMemberIndex =
              members.findIndex(
                (member) =>
                  member.midiPitch
                    === event.singleTieMidiPitch,
              );

            if (targetMemberIndex < 0) {
              fail(
                "single tied chord member is absent after chord ordering",
              );
            }

            let rebuilt = writtenNoteBrf;
            let previousPrefix =
              writtenNoteBrf;

            for (
              let intervalIndex = 0;
              intervalIndex < intervals.length;
              intervalIndex += 1
            ) {
              const prefix =
                encodeAtomicChord({
                  writtenNote:
                    atomicWrittenNote,
                  intervals:
                    intervals.slice(
                      0,
                      intervalIndex + 1,
                    ),
                }).brf;

              if (
                !prefix.startsWith(
                  previousPrefix,
                )
              ) {
                fail(
                  "atomic chord interval encoding is not prefix-composable",
                );
              }

              rebuilt +=
                prefix.slice(
                  previousPrefix.length,
                );

              if (
                intervalIndex
                  === targetMemberIndex
              ) {
                rebuilt +=
                  singleTieBrf;
              }

              previousPrefix = prefix;
            }

            chordBrf = rebuilt;
          }
        }

        const core =
          gracePrefixBrf(event.grace)
          + articulationPrefixBrf(
              event.articulations,
            )
          + chordBrf;

        const dynamicBrf =
          dynamicPrefixBrf(event.dynamic, core);

        emitted =
          directionMarkPrefixBrf(event)
          + wordExpressionPrefixBrf(
            event.wordExpressions,
            dynamicBrf + core,
          )
          + dynamicBrf
          + core
          + simpleSlurSuffixBrf(event.slurAfter)
          + directionMarkSuffixBrf(event);

        previousWritten = written;
        forceNextOctave =
          event.hairpinStop !== undefined;
        trace.push(
          freezeTrace({
            measureIndex,
            eventIndex,
            kind: event.kind,
            written,
            members,
            emittedBrf: emitted,
          }),
        );
        brf += emitted;
        continue;
      } else {
        const exhaustive: never = event;
        fail(`unsupported event ${(exhaustive as { kind?: string }).kind ?? "unknown"}`);
      }

      trace.push(
        freezeTrace({
          measureIndex,
          eventIndex,
          kind: event.kind,
          emittedBrf: emitted,
        }),
      );
      brf += emitted;
    }

    if (measure.terminalRepeat === true) {
      brf += STATEFUL_TERMINAL_REPEAT_BRF;
    }

    if (measureIndex + 1 < input.measures.length) {
      brf +=
        measure.events.some((event) => event.kind === "keyboard-parallel")
          ? "\n"
          : " ";
    }
  }

  return Object.freeze({
    brf,
    unicode: brfAsciiToUnicode(brf),
    profileId: MIDI_STATEFUL_PROFILE_ID,
    chordProfileId: MIDI_CHORD_PROFILE_ID,
    ...(keyboardDirectionalProfileUsed
      ? {
          keyboardChordProfileId:
            KEYBOARD_DIRECTIONAL_CHORD_PROFILE_ID,
        }
      : {}),
    profileDisclosureRequired: true,
    trace: Object.freeze(trace),
  });
}
