// Generated by Phase 14.6a. Do not hand-edit.
// Atomic Music Braille encoder foundation.
// NotationScore integration remains Phase 14.7.

import { brfAsciiToUnicode } from "./braille-ascii.js";

export const NOTE_SYMBOLS_BY_FAMILY = {
  "wholeOr16th": {
    "C": "y",
    "D": "z",
    "E": "&",
    "F": "=",
    "G": "(",
    "A": "!",
    "B": ")"
  },
  "halfOr32nd": {
    "C": "n",
    "D": "o",
    "E": "p",
    "F": "q",
    "G": "r",
    "A": "s",
    "B": "t"
  },
  "quarterOr64th": {
    "C": "?",
    "D": ":",
    "E": "$",
    "F": "]",
    "G": "\\",
    "A": "[",
    "B": "w"
  },
  "eighthOr128th": {
    "C": "d",
    "D": "e",
    "E": "f",
    "F": "g",
    "G": "h",
    "A": "i",
    "B": "j"
  }
} as const;
export const REST_SYMBOLS_BY_FAMILY = {
  "wholeOr16th": "m",
  "halfOr32nd": "u",
  "quarterOr64th": "v",
  "eighthOr128th": "x"
} as const;
export const OCTAVE_PREFIXES = {
  "sub": "@@",
  "1": "@",
  "2": "^",
  "3": "_",
  "4": "\"",
  "5": ".",
  "6": ";",
  "7": ",",
  "super": ",,"
} as const;
export const ACCIDENTAL_SYMBOLS = {
  "sharp": "%",
  "doubleSharp": "%%",
  "flat": "<",
  "doubleFlat": "<<",
  "natural": "*",
  "quarterSharp": "@%",
  "quarterFlat": "@<",
  "threeQuarterSharp": "_%",
  "threeQuarterFlat": "_<"
} as const;
export const GROUPING_SYMBOLS = {
  "tripletSingleCell": "2",
  "tripletThreeCell": "_3'",
  "groupTwo": "_2'",
  "groupTen": "_10'"
} as const;
export const INTERVAL_SYMBOLS = {
  "2": "/",
  "3": "+",
  "4": "#",
  "5": "9",
  "6": "0",
  "7": "3",
  "8": "-"
} as const;
export const TIE_SYMBOLS = {
  "single": "@c",
  "chord": ".c"
} as const;
export const METER_DENOMINATORS = [
  1,
  2,
  4,
  8,
  16,
  32,
  64
] as const;
export const NORMAL_MEASURE_SEPARATOR = " " as const;

export type MusicNoteName = "C" | "D" | "E" | "F" | "G" | "A" | "B";
export type MusicValue = "whole" | "half" | "quarter" | "eighth" | "16th" | "32nd" | "64th" | "128th";
export type ExplicitAccidental =
  | "sharp"
  | "doubleSharp"
  | "flat"
  | "doubleFlat"
  | "natural"
  | "quarterSharp"
  | "quarterFlat"
  | "threeQuarterSharp"
  | "threeQuarterFlat";
export type TieKind = "single" | "chord";

export interface BrailleEmission {
  readonly brf: string;
  readonly unicode: string;
}

export interface AtomicNoteInput {
  readonly step: MusicNoteName;
  readonly scientificOctave: number;
  readonly value: MusicValue;
  readonly accidental?: ExplicitAccidental;
  readonly augmentationDots?: number;
  readonly tie?: boolean;
  readonly includeOctave?: boolean;
  readonly tripletStart?: boolean;
}

export interface AtomicRestInput {
  readonly value: MusicValue;
  readonly augmentationDots?: number;
  readonly tripletStart?: boolean;
}

export interface AtomicChordIntervalInput {
  readonly diatonicInterval: 2 | 3 | 4 | 5 | 6 | 7 | 8;
  readonly accidental?: ExplicitAccidental;
}

export interface AtomicChordInput {
  readonly writtenNote: AtomicNoteInput;
  readonly intervals: readonly AtomicChordIntervalInput[];
  readonly tieAll?: boolean;
}

const VALUE_TO_FAMILY = {
  whole: "wholeOr16th",
  "16th": "wholeOr16th",
  half: "halfOr32nd",
  "32nd": "halfOr32nd",
  quarter: "quarterOr64th",
  "64th": "quarterOr64th",
  eighth: "eighthOr128th",
  "128th": "eighthOr128th",
} as const;

const UPPER_DIGIT = {
  "1": "a",
  "2": "b",
  "3": "c",
  "4": "d",
  "5": "e",
  "6": "f",
  "7": "g",
  "8": "h",
  "9": "i",
  "0": "j",
} as const;

function fail(message: string): never {
  throw new Error(`MUSIC_BRAILLE_ENCODER_ERROR: ${message}`);
}

function emission(brf: string): BrailleEmission {
  return Object.freeze({ brf, unicode: brfAsciiToUnicode(brf) });
}

function assertAugmentationDots(count: number): void {
  if (!Number.isInteger(count) || count < 0 || count > 3) {
    fail(`augmentationDots must be an integer in 0..3, got ${count}`);
  }
}

export function noteCellBrf(step: MusicNoteName, value: MusicValue): string {
  const family = VALUE_TO_FAMILY[value];
  const mapping = NOTE_SYMBOLS_BY_FAMILY[family];
  const token = mapping[step];
  if (typeof token !== "string") fail(`unsupported note ${step} ${value}`);
  return token;
}

export function restCellBrf(value: MusicValue): string {
  const family = VALUE_TO_FAMILY[value];
  const token = REST_SYMBOLS_BY_FAMILY[family];
  if (typeof token !== "string") fail(`unsupported rest ${value}`);
  return token;
}

export function octavePrefixBrf(scientificOctave: number): string {
  if (!Number.isInteger(scientificOctave) || scientificOctave < 0 || scientificOctave > 8) {
    fail(`scientificOctave must be an integer in 0..8, got ${scientificOctave}`);
  }
  if (scientificOctave === 0) return OCTAVE_PREFIXES.sub;
  if (scientificOctave === 8) return OCTAVE_PREFIXES.super;
  const token = OCTAVE_PREFIXES[String(scientificOctave) as keyof typeof OCTAVE_PREFIXES];
  if (typeof token !== "string") fail(`missing octave token for scientific octave ${scientificOctave}`);
  return token;
}

export function accidentalBrf(accidental: ExplicitAccidental): string {
  const token = ACCIDENTAL_SYMBOLS[accidental];
  if (typeof token !== "string") fail(`unsupported accidental ${accidental}`);
  return token;
}

export function upperCellNumberBrf(value: number): string {
  if (!Number.isInteger(value) || value < 0) {
    fail(`upper-cell number must be a non-negative integer, got ${value}`);
  }
  return String(value).split("").map((digit) => {
    const token = UPPER_DIGIT[digit as keyof typeof UPPER_DIGIT];
    if (!token) fail(`unsupported decimal digit ${digit}`);
    return token;
  }).join("");
}

export function keySignatureBrf(sharpsFlats: number): string {
  if (!Number.isInteger(sharpsFlats) || sharpsFlats < -7 || sharpsFlats > 7) {
    fail(`key signature sf must be an integer in -7..7, got ${sharpsFlats}`);
  }
  if (sharpsFlats === 0) return "";
  const count = Math.abs(sharpsFlats);
  const sign = sharpsFlats > 0 ? ACCIDENTAL_SYMBOLS.sharp : ACCIDENTAL_SYMBOLS.flat;
  if (count <= 3) return sign.repeat(count);
  return `#${upperCellNumberBrf(count)}${sign}`;
}

export function simpleMeterBrf(numerator: number, denominator: number): string {
  if (!Number.isInteger(numerator) || numerator < 1 || numerator > 99) {
    fail(`meter numerator must be an integer in 1..99, got ${numerator}`);
  }
  if (!(METER_DENOMINATORS as readonly number[]).includes(denominator)) {
    fail(`unsupported simple meter denominator ${denominator}`);
  }
  return `#${upperCellNumberBrf(numerator)}${String(denominator)}`;
}

export function tripletIndicatorBrf(): string {
  return GROUPING_SYMBOLS.tripletSingleCell;
}

export function intervalBrf(interval: 2 | 3 | 4 | 5 | 6 | 7 | 8): string {
  const token = INTERVAL_SYMBOLS[String(interval) as keyof typeof INTERVAL_SYMBOLS];
  if (typeof token !== "string") fail(`unsupported diatonic interval ${interval}`);
  return token;
}

export function tieBrf(kind: TieKind): string {
  if (kind === "single") return TIE_SYMBOLS.single;
  if (kind === "chord") return TIE_SYMBOLS.chord;
  fail(`unsupported tie kind ${String(kind)}`);
}

export function encodeAtomicNote(input: AtomicNoteInput): BrailleEmission {
  const dots = input.augmentationDots ?? 0;
  assertAugmentationDots(dots);
  let brf = "";
  if (input.tripletStart) brf += tripletIndicatorBrf();
  if (input.accidental) brf += accidentalBrf(input.accidental);
  if (input.includeOctave !== false) brf += octavePrefixBrf(input.scientificOctave);
  brf += noteCellBrf(input.step, input.value);
  brf += "'".repeat(dots);
  if (input.tie) brf += tieBrf("single");
  return emission(brf);
}

export function encodeAtomicRest(input: AtomicRestInput): BrailleEmission {
  const dots = input.augmentationDots ?? 0;
  assertAugmentationDots(dots);
  let brf = "";
  if (input.tripletStart) brf += tripletIndicatorBrf();
  brf += restCellBrf(input.value);
  brf += "'".repeat(dots);
  return emission(brf);
}

export function encodeAtomicChord(input: AtomicChordInput): BrailleEmission {
  if (input.intervals.length === 0) fail("atomic chord requires at least one interval member");
  const written = encodeAtomicNote({ ...input.writtenNote, tie: false }).brf;
  let brf = written;
  for (const member of input.intervals) {
    if (member.accidental) brf += accidentalBrf(member.accidental);
    brf += intervalBrf(member.diatonicInterval);
  }
  if (input.tieAll) brf += tieBrf("chord");
  return emission(brf);
}

export function encodeKeySignature(sharpsFlats: number): BrailleEmission {
  return emission(keySignatureBrf(sharpsFlats));
}
export function encodeSimpleMeter(numerator: number, denominator: number): BrailleEmission {
  return emission(simpleMeterBrf(numerator, denominator));
}
export function encodeTripletIndicator(): BrailleEmission { return emission(tripletIndicatorBrf()); }
export function encodeInterval(interval: 2 | 3 | 4 | 5 | 6 | 7 | 8): BrailleEmission { return emission(intervalBrf(interval)); }
export function encodeTie(kind: TieKind): BrailleEmission { return emission(tieBrf(kind)); }
export function fullMeasureInAccordBrf(): string { return "<>"; }
export function partMeasureInAccordBrf(): string { return '"1'; }
export function measureDivisionBrf(): string { return ".k"; }
export function transcriberAddedRestPrefixBrf(): string { return '"'; }
export function encodeMeasureSeparator(): BrailleEmission { return emission(NORMAL_MEASURE_SEPARATOR); }
